name: Push Coder Template
on:
  push:
    branches: [main]
    paths:
      - "coder/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Coder CLI
        run: curl -fsSL https://coder.com/install.sh | sh

      - name: Push template
        env:
          CODER_URL: https://coder.noel.codespace.sh
          CODER_SESSION_TOKEN: ${{ secrets.CODER_TOKEN }}
        run: |
          coder templates push example --directory coder --yes
